---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(haven)
library(countrycode)
theme_set(theme_light())

diplomatic_core_raw <- read_dta("diplomatic_core.replication.dta")

diplomatic_core_raw %>% View()

glimpse(diplomatic_core_raw)

diplomatic_core_raw %>% 
  count(cowid, sort = T)

diplomatic_core_raw <- diplomatic_core_raw %>% 
  mutate(country = countrycode(cowid, origin = "cown", destination = "iso3c")) %>% 
  select(country, everything())
```

```{r}
by_category <- diplomatic_core_raw %>% 
  select(year, country, bi_SOS, bi_PRE, bi_str_SOS, bi_str_PRE) %>% 
  group_by(year) %>% 
  summarize(total_sos = sum(bi_SOS == 1), 
            total_str_sos = sum(bi_str_SOS == 1), 
            total_pre = sum(bi_PRE == 1), 
            total_str_pre = sum(bi_str_PRE == 1)) 

pre_p <- by_category %>% 
  gather(category, value, total_pre, total_str_pre) %>% 
  ggplot(aes(year, value, linetype = category)) +
  geom_line(size = .7)  +
  geom_smooth(method = "loess", se = F) +
  scale_x_continuous(breaks = seq(1940, 2010, 10)) +
  scale_y_continuous(limits = c(0, 30), 
                     breaks = seq(0, 30, 10)) +
  labs(title = "大統領(President)", 
       x = " ", 
       y = " ") +
  annotate("text", x = 1988, y = 21, label = "全体訪問", family = "HiraKakuProN-W6") +
  annotate("text", x = 2000, y = 2, label = "二国間訪問", family = "HiraKakuProN-W6") +
  # annotate("segment", x = 1989, xend = 1993, y = 20, yend = 18, colour = "black", size = .5, arrow = arrow(length = unit(2, "mm"))) +
  # annotate("segment", x = 1998, xend = 2000, y = 3, yend = 5, colour = "black", size = .5, arrow = arrow(length = unit(2, "mm"))) +
  theme_bw(base_family = "HiraKakuProN-W6") +
  theme(legend.position = "none")  + 
  theme(plot.title = element_text(size = 9)) 
  
```

```{r}
sos_p <- by_category %>% 
  gather(category, value, total_sos, total_str_sos) %>% 
  ggplot(aes(year, value, linetype = category)) +
  geom_line(size = .7)  +
  geom_smooth(method = "loess", se = F) +
  scale_x_continuous(breaks = seq(1940, 2010, 10)) +
  scale_y_continuous(limits = c(0, 60), 
                     breaks = seq(0, 60, 10)) +
  labs(title = "国務大臣(Secretary of State)", 
       x = " ", 
       y = " ") +
  annotate("text", x = 1983, y = 35, label = "全体訪問", family = "HiraKakuProN-W6") +
  annotate("text", x = 2000, y = 10, label = "二国間訪問", family = "HiraKakuProN-W6") +
  # annotate("segment", x = 1987, xend = 1990, y = 34, yend = 32, colour = "black", size = .5, arrow = arrow(length = unit(2, "mm"))) +
  # annotate("segment", x = 1998, xend = 1995, y = 4, yend = 6, colour = "black", size = .5, arrow = arrow(length = unit(2, "mm"))) +
  theme_bw(base_family = "HiraKakuProN-W6") +
  theme(legend.position = "none") + 
  theme(plot.title = element_text(size = 9)) 
  
```
# Place plots side by side
```{r}
library(cowplot)
library(gridExtra)

title_gg <- ggdraw() +
  draw_label("図 首脳外交の時代？（アメリカ、1946-2012)", 
             size = 12, 
             fontfamily = "HiraKakuProN-W6")

subtitle_gg <- ggdraw() +
  draw_label("\n [出典] Levovic and Saunders 2014 \n ", 
             size = 10, 
             fontfamily = "HiraKakuProN-W6")

gridded <- plot_grid(pre_p, sos_p, nrow = 1)

plot_grid(title_gg, gridded, subtitle_gg, ncol = 1, rel_heights = c(0.35, 3))
```

logistic bi_str_PRE mil_ratio USmilaid allies USdefense USdefense_EUR UStrade energypc USalign UNpart mpower term2 TRU EIS KEN JOH NIX FOR CAR REA CLI GWB demo bi_L14_SOS bi_L14_PRE bi_L58_SOS bi_L58_PRE EUR AFR MEA SCA EAP, vce(cluster cowid) coef
```{r}
library(broom)

mod_1 <- glm(bi_PRE ~ mil_ratio + USmilaid + allies + USdefense + USdefense_EUR + energypc + USalign + UNpart + mpower + term2 + demo + bi_L1_SOS + bi_L1_PRE + bi_str_L1_SOS + bi_str_L1_PRE +EUR + AFR + MEA + SCA + EAP, data = diplomatic_core_raw, family = binomial(link = "logit"))

mod_2 <- glm(bi_str_PRE ~ mil_ratio + USmilaid + allies + USdefense + USdefense_EUR + energypc + USalign + UNpart + mpower + term2 + demo + bi_L14_SOS + bi_L14_PRE + bi_L58_SOS + bi_L58_PRE + EUR + AFR + MEA + SCA + EAP, data = diplomatic_core_raw, family = binomial(link = "logit")) %>% 
  tidy()
```
```{r}
library(coefplot)

coefplot(mod_1)
```

